package net.harutiro.uwbanchorsystem.feature.serial.Entity

data class SyncPacket (
    val uCIRangingNotification: String,
    val uCIPayloadLength:String,
    val sequenceCounter:String,
    val sessionId:String,
    val rfu1:String,
    val rangingInterval:String,
    val measurementType:String,
    val rfu2:String,
    val macAddressIndicator8Bytes:String,
    val sessionIdOfPrimarySession0ifSessionNotPartOfHybridUwbSession:String,
    val rfu3:String,
    val numberOfRangingMeasurement:String,
    val macAddress:String,
    val status:String,
    val messageControl:String,
    val frameType:String,
    val nLos:String,
    val aoaAzimuth:Double,
    val aoaAzimuthFOM: Double,
    val aoaElevation:Double,
    val aoaElevationFOM:Double,
    val frameCounter:String,
    val rxTimestamp:String,
    val txTimestamp:String,
    val vendorSpecificLength:String,
    val vendorExtensionLength:String,
    val rssiRx1:String,
    val rssiRx2:String,
    val numberOfPDoA:Int,
    val pDoA1:Double,
    val pDoA2:Double,
    val antennaPairInfo:String,
    val wifiCoexStatus:String,
    val authenticityInfoPresence:String,
)